// <auto-generated />
using FineAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FineAPI.Migrations
{
    [DbContext(typeof(FineContext))]
    [Migration("20220113134842_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FineAPI.Entities.Fine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvtoId")
                        .HasColumnType("int")
                        .HasColumnName("avto_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("StatusFine")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_fine");

                    b.Property<int>("SumaryFine")
                        .HasColumnType("int")
                        .HasColumnName("sumary_fine");

                    b.Property<int>("TypeFineId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeFineId");

                    b.ToTable("fine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvtoId = 1,
                            PersonId = 6,
                            StatusFine = "Не оплачен",
                            SumaryFine = 30000,
                            TypeFineId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvtoId = 2,
                            PersonId = 7,
                            StatusFine = "Не оплачен",
                            SumaryFine = 500,
                            TypeFineId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvtoId = 1,
                            PersonId = 7,
                            StatusFine = "Не оплачен",
                            SumaryFine = 1500,
                            TypeFineId = 3
                        });
                });

            modelBuilder.Entity("FineAPI.Entities.TypeFine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("article");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_fine");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Article = "264.1",
                            Name = "Вождение в нетрезвом виде"
                        },
                        new
                        {
                            id = 2,
                            Article = "12.9",
                            Name = "Превышение скорости"
                        },
                        new
                        {
                            id = 3,
                            Article = "124.2",
                            Name = "Парковка в неположеном месте"
                        });
                });

            modelBuilder.Entity("FineAPI.Entities.Fine", b =>
                {
                    b.HasOne("FineAPI.Entities.TypeFine", "TypeFine")
                        .WithMany()
                        .HasForeignKey("TypeFineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeFine");
                });
#pragma warning restore 612, 618
        }
    }
}
