// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationAppointService.Models;

namespace RegistrationAppointService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211207195753_RegistrationAppointService7")]
    partial class RegistrationAppointService7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DocumentService", b =>
                {
                    b.Property<int>("DocumentsId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("DocumentsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("DocumentService");
                });

            modelBuilder.Entity("RegistrationAppointService.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Паспорт гражданина РФ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Водительское удостоверение"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Документ о сдаче экзамена ПДД"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Договор купли-продажи транспортного средства"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Страховой полис"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Технический паспорт транспортного средства"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Документ собственника транспортного средства"
                        });
                });

            modelBuilder.Entity("RegistrationAppointService.Models.GibddOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("GibddOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lat = 56.433999999999997,
                            Lon = 54.432000000000002,
                            Name = "Управление ГИБДД УМВД России по Владимирской обл.",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Lat = 57.433999999999997,
                            Lon = 55.432000000000002,
                            Name = "Отдел ГИБДД по Суздальскому району",
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("RegistrationAppointService.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("lat")
                        .HasColumnType("float");

                    b.Property<double>("lon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Владимирская область",
                            lat = 56.129057000000003,
                            lon = 40.406635000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "Московская область",
                            lat = 55.753219999999999,
                            lon = 37.622512999999998
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ивановская область",
                            lat = 57.000352999999997,
                            lon = 40.973930000000003
                        });
                });

            modelBuilder.Entity("RegistrationAppointService.Models.RegistrationService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("GibddOfficeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceDateTimeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GibddOfficeId");

                    b.HasIndex("ServiceDateTimeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RegistrationServices");
                });

            modelBuilder.Entity("RegistrationAppointService.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Постановка автомобиля на учёт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Получение водительского удостоверения"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Замена водительского удостоверения"
                        });
                });

            modelBuilder.Entity("RegistrationAppointService.Models.ServiceDateTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceDateTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "8:00"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "8:15"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "8:30"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = false,
                            Time = "8:45"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "9:00"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "9:15"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "9:30"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "9:45"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "10:00"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "10:15"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "10:30"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "10:45"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "11:00"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "11:15"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "11:30"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "11:45"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "12:00"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "13:00"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "13:15"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "13:30"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "13:45"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "14:00"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFree = true,
                            Time = "14:15"
                        });
                });

            modelBuilder.Entity("DocumentService", b =>
                {
                    b.HasOne("RegistrationAppointService.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrationAppointService.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistrationAppointService.Models.GibddOffice", b =>
                {
                    b.HasOne("RegistrationAppointService.Models.Region", "Region")
                        .WithMany("GibddOffices")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RegistrationAppointService.Models.RegistrationService", b =>
                {
                    b.HasOne("RegistrationAppointService.Models.GibddOffice", "GibddOffice")
                        .WithMany("RegistrationServices")
                        .HasForeignKey("GibddOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrationAppointService.Models.ServiceDateTime", "ServiceDateTime")
                        .WithMany()
                        .HasForeignKey("ServiceDateTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrationAppointService.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GibddOffice");

                    b.Navigation("Service");

                    b.Navigation("ServiceDateTime");
                });

            modelBuilder.Entity("RegistrationAppointService.Models.GibddOffice", b =>
                {
                    b.Navigation("RegistrationServices");
                });

            modelBuilder.Entity("RegistrationAppointService.Models.Region", b =>
                {
                    b.Navigation("GibddOffices");
                });
#pragma warning restore 612, 618
        }
    }
}
